# Generated by Django 2.2.3 on 2019-07-16 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BooksApp', '0002_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='about',
            field=models.TextField(default='null'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='picture',
            field=models.ImageField(default='https://www.bookshare.org/cms/sites/default/files/styles/panopoly_image_original/public/images/media/book_0.png?itok=1g_hENwd', upload_to='book_pic'),
            preserve_default=False,
        ),
    ]
